<?php
$row = $this->getRow();
?>
<table>
  <tr>
    <td><h3>Edit Item<h3></td>
    <td><a class="btn btn-primary mx-2" href="<?php echo $this->getModelUrl()->getUrl('grid',null,null,true); ?>">cancel</a> </td>
    <form action="<?php echo $this->getModelUrl()->getUrl('save'); ?>" method="POST">
      <td><button class="btn btn-primary"> save</button></td>
    </tr>
  </table>
<table class="table table-bordered">
<tr>
	<th>sku</th>
	 <td><input type="text" name="item[sku]" value="<?php echo $row->sku;?>"></td>
</tr>
<tr>
	<th>status</th>
	<td><select name="item[status]">
        <?php foreach ($row->getResource()->getStatusOptions() as $key => $value): ?>
        <option value="<?php echo $key ?>"<?php if($row->getstatus() == $key){ echo 'selected'; } ?>><?php echo $value ?></option>
        <?php endforeach; ?>
      </select></td>
</tr>
<tr>
<?php foreach ($this->getAttributes() as $key => $value): ?>
	<tr><th><?php echo$value->name; ?></th>
	<td><?php $this->getLayout()->createBlock("Eav_Attribute_inputType")->setAttribute($value)->setRow($row)->render();?></td><tr>
<?php endforeach ?>	
</tr>
</table>
</form>