 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand mx-1" href="<?php echo $this->getUrl('index', 'product', null, true); ?>">product</a>
  <a class="navbar-brand" href="<?php echo $this->getUrl('index', 'category', null, true); ?>">category</a>
  <a class="navbar-brand" href="<?php echo $this->getUrl('index', 'customer', null, true); ?>">customer</a>
  <a class="navbar-brand" href="<?php echo $this->getUrl('index', 'vendor', null, true); ?>">vendor</a>
  <a class="navbar-brand" href="<?php echo $this->getUrl('index', 'salesman', null, true); ?>">salesman</a>
  <a class="navbar-brand" href="<?php echo $this->getUrl('index', 'shippingMethod', null, true); ?>">shipping method</a>
  <a class="navbar-brand" href="<?php echo $this->getUrl('index', 'paymentMethod', null, true); ?>">payment method</a>
  <a class="navbar-brand" href="<?php echo $this->getUrl('index', 'admin', null, true); ?>">Admin</a>
  <a class="navbar-brand" href="<?php echo $this->getUrl('index', 'eav_attribute', null, true); ?>">eav</a>
  <a class="navbar-brand" href="<?php echo $this->getUrl('index', 'order', null, true); ?>">Order</a>
  <a class="navbar-brand" href="<?php echo $this->getUrl('index', 'item', null, true); ?>">item</a>
  <a class="navbar-brand" href="<?php echo $this->getUrl('index', 'brand', null, true); ?>">brand</a>
</nav>
