<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title><?php echo $this->getTitle(); ?></title>
	<?php foreach ($this->getStysheets() as $css): ?>
	<link rel="stylesheet" href="<?php echo $css ?>">
	<?php endforeach ?>
	<?php foreach ($this->getAllJs() as $src): ?>
	<script type="text/javascript" src="<?php echo $src ?>" ></script>
	<?php endforeach ?>
</head>