<?php
$row = $this->getData('product');
?>
<table>
  <tr>
    <td><h3>Edit Product<h3></td>
    <td><a class="btn btn-primary mx-2" href="<?php echo $this->getModelUrl()->getUrl('grid',null,null,true); ?>">cancel</a> </td>
    <form action="<?php echo $this->getModelUrl()->getUrl('save'); ?>" method="POST">
      <td><button class="btn btn-primary"> save</button></td>
    </tr>
  </table>
  <table class="table table-bordered">
    <tr>
      <th>NAME</th>
      <td><input type="text" name="product[name]" value="<?php echo $row->name;?>"></td>
    </tr>
    <tr>
      <th>SKU</th>
      <td><input type="text" name="product[sku]" value="<?php echo $row->sku;?>"></td>
    </tr>
    <tr>
      <th>COST</th>
      <td><input type="number" name="product[cost]" value="<?php echo $row->cost;?>"></td>
    </tr>
    <tr>
      <th>PRICE</th>
      <td><input type="number" name="product[price]" value="<?php echo $row->price;?>"></td>
    </tr>
    <tr>
      <th>QUANTITY</th>
      <td><input type="number" name="product[quantity]" value="<?php echo $row->quantity;?>"></td>
    </tr>
    <tr>
      <th>DESCRIPTION</th>
      <td><input type="text" name="product[description]" value="<?php echo $row->description;?>"></td>
    </tr>
    <tr>
      <th>STATUS</th>
      <td><select name="product[status]" >
        <?php foreach ($row->getStatusOptions() as $key => $value): ?>
        <option value="<?php echo $key ?>"<?php if($row->getstatus() == $key){ echo 'selected'; } ?>><?php echo $value ?></option>
        <?php endforeach; ?>
      </select></td>
    </tr>
    <tr>
      <th>COLOR</th>
      <td><select name="product[color]" value="<?php echo $color?>" >
        <option value="red"name="Available">red</option>
        <option value="green"name="unavailable">green</option>
        <option value="blue"name="unavailable">blue</option>
      </select></td>
    </tr>
    <tr>
      <th>MATERIAL</th>
      <td><input type="text" name="product[material]" value="<?php echo $row->material;?>"></td>
    </tr>
    <tr>
      <?php if ($this->getAttributes()): ?>
      <?php foreach ($this->getAttributes() as $key => $value): ?>
      <tr><th><?php echo$value->name; ?></th>
      <td><?php $this->getLayout()->createBlock("Eav_Attribute_inputType")->setAttribute($value)->setRow($row)->render();?></td><tr>
      <?php endforeach ?>
      <?php endif ?>
    </tr>
  </form>
</table>