<?php $attribute = $this->getAttribute(); ?>
<?php $row = $this->getRow()  ?>
<?php $id = $attribute->attribute_id; ?>
<?php $ids=explode(',', $row->$id) ?>
<?php foreach ($attribute->getOptions() as $key => $option): ?>
<input type="checkbox" name="attribute[<?php echo $attribute->backend_type ?>][<?php echo $attribute->getId() ?>][]" value="<?php echo $option->option_id; ?>" <?php if(in_array($option->option_id, $ids)){echo 'checked';} ?>>
<label><?php echo $option->name; ?></label><br>
<?php endforeach ?>
