<?php
$address = $this->getCustomerAddress();
?>
<div><h3>CUSTOMER ADDRESS</h3></div>
<table class="table table-bordered">
  <tr>
    <th>ADDRESS_ID</th>
    <th>ADDRESS</th>
    <th>CITY</th>
    <th>STATE</th>
    <th>COUNTRY</th>
    <th>ZIP_CODE</th>
  </tr>
  <tr>
    <td><?php echo $address->address_id ?> </td>
    <td><?php echo $address->address ?></td>
    <td><?php echo $address->city ?></td>
    <td><?php echo $address->state ?></td>
    <td><?php echo $address->country ?></td>
    <td><?php echo $address->zip_code ?></td>
  </tr>
</table>