<?php
$row = $this->getRow();
?>
<table>
  <tr>
    <td><h3>Edit brand<h3></td>
    <td><a  class="btn btn-primary mx-2" onclick="ajax.setUrl('<?php echo $this->getUrl('grid',null,null,true); ?>').call()">cancel</a> </td>
    </tr>
  </table>
    <form id="brand" action="<?php echo $this->getUrl('save'); ?>" method="POST" enctype="multipart/form-data">
  <table class="table table-bordered">
      <button class="btn btn-primary" type="submit" onclick="ajax.setUrl('<?php echo $this->getUrl('save'); ?>').setForm('brand').setMethod('post').call()" > save</button>
    <tr>
      <th>NAME</th>
      <td><input type="text" name="brand[name]" value="<?php echo $row->name;?>"></td>
    </tr>
    <tr>
      <th>DESCROPTION</th>
      <td><textarea type="text" name="brand[description]" ><?php echo $row->description;?></textarea></td>
    </tr>
    <tr>
      <th>IMAGE</th>
      <td> <input type="file" name="fileToUpload" id = "file" multiple></td>
    </tr>
</table>
  </form>