<?php
$brand = $this->getRow();
?>
<table>
  <tr>
    <td><h3>Edit brand<h3></td>
    <td><a class="btn btn-primary mx-2" href="<?php echo $this->getModelUrl()->getUrl('grid',null,null,true); ?>">cancel</a> </td>
    <form action="<?php echo $this->getModelUrl()->getUrl('save'); ?>" method="POST" enctype="multipart/form-data">
      <td><button class="btn btn-primary"> save</button></td>
    </tr>
  </table>
  <table class="table table-bordered">
    <tr>
      <th>NAME</th>
      <td><input type="text" name="brand[name]" value="<?php echo $brand->name;?>"></td>
    </tr>
    <tr>
      <th>DESCROPTION</th>
      <td><textarea type="text" name="brand[description]" ><?php echo $brand->description;?></textarea></td>
    </tr>
    <tr>
      <th>IMAGE</th>
      <td> <input type="file" name="fileToUpload" id = "file" multiple></td>
    </tr>
    <tr>
      <?php if ($this->getAttributes()): ?>
      <?php foreach ($this->getAttributes() as $key => $value): ?>
      <tr><th><?php echo$value->name; ?></th>
      <td><?php $this->getLayout()->createBlock("Eav_Attribute_inputType")->setAttribute($value)->setRow($brand)->render();?></td><tr>
      <?php endforeach ?>
      <?php endif ?>
    </tr>
  </form>
</table>