<?php
$admins = $this->getAdmins();
?>
<div><div><h3>admin</h3></div><div style="margin-left:640px;margin-top: 15px;">
<a class="btn btn-primary" href="<?php echo $this->getUrl('add'); ?>">
	add admin
</a></div></div>
<table class="table table-bordered">
	<tr>
		<th>ADMIN_ID</th>
		<th>NAME</th>
		<th>EMAIL</th>
		<th>STATUS</th>
		<th></th>
		<th></th>
	</tr>
	<?php if (!$admins): ?>
	<td colspan="6" >data not found </td>
	<?php else:?>
	
	<?php foreach ($admins->getData() as $admin): ?>
	<tr>
		<td><?php echo $admin->admin_id; ?></td>
		<td><?php echo $admin->name; ?></td>
		<td><?php echo $admin->email; ?></td>
		<td><?php echo $admin->getstatustext(); ?></td>
		<td><a href="<?php echo $this->getUrl('edit', 'admin', ['admin_id' => $admin->admin_id]); ?>">edit</a></td>
		<td><a href="<?php echo $this->getUrl('delete','admin',['admin_id' => $admin->admin_id]); ?>">delete<a></td>
	</tr>
	<?php endforeach; ?>
	<?php endif;?>
</table>