<?php
$payment_method = $this->getData('PaymentMethod');
?>
<table>
  <tr>
    <td><h3><h3></td>
    <td><a class="btn btn-primary mx-2" href="<?php echo $this->getModelUrl()->getUrl('grid',null,null,true); ?>">cancel</a> </td>
    <form action="<?php echo $this->getModelUrl()->getUrl('save'); ?>" method="POST">
      <td><button class="btn btn-primary">save</button></td>
    </tr>
  </table>
  <br>
  <table class="table table-bordered">
    <form action="update_payment_method.php" method="GET">
      <tr>
        <th>NAME</th>
        <td><input type="text" name="payment_method[name]" value="<?php echo $payment_method->name ?>"></td>
      </tr>
      <th> STATUS</th>
      <td> <select name="payment_method[status]"   >
        <?php foreach ($payment_method->getResource()->getStatusOptions() as $key => $value): ?>
        <option value="<?php echo $key ?>"name="available" <?php if($payment_method->getstatus() == $key){ echo 'selected'; } ?>><?php echo $value ?></option>
        <?php endforeach; ?>
      </select> </td>
    </tr>
  </form>
</table>