<?php
$payment_methods = $this->getCollection();
?>
<div><div><h3>PAYMENT METHOD</h3></div><div style="margin-left:640px;margin-top: 15px;"><a  class="btn btn-primary" href="<?php echo $this->getUrl('add'); ?>">
add payment method
</a></div></div>
<table class="table table-bordered">
<tr>
  <th>PAYMENT_METHOD_ID</th>
  <th>NAME</th>
  <th>STATUS</th>
  <th></th>
  <th></th>
</tr>
<?php if (!$payment_methods): ?>
<td colspan="5" >data not found </td>
<?php else:?>
<?php
foreach ($payment_methods as $payment_method): ?>
<tr>
  <td><?php echo $payment_method->payment_method_id ?></td>
  <td> <?php echo $payment_method->name ?></td>
  <td> <?php echo $payment_method->getStatusText() ?></td>
  <td><a href="<?php echo $this->getUrl('edit', null, ['payment_method_id' => $payment_method->payment_method_id]); ?>">edit</a></td>
  <td><a href="<?php echo $this->getUrl('delete', null, ['payment_method_id' => $payment_method->payment_method_id]); ?>?a=delete&c=paymentmethod&payment_method_id=<?php echo $payment_method->payment_method_id ?>">delete<a></td>
</tr>
<?php endforeach; ?>
<?php endif;?>
</table>