<?php
$row = $this->getRow();
$entities = $this->getEntities();
$options = $row->getOptions();
?>
<div class="modal-body">
	<table>
		<tr>
			<td><h3>Edit Attributes<h3></td>
			<td><a class="btn btn-primary mx-2" onclick="ajax.setUrl('<?php echo $this->getUrl('grid',null,null,true); ?>').call()">cancel</a> </td>
			<td><button id="subtn" class="btn btn-primary" type="button" onclick="ajax.setUrl('<?php echo $this->getUrl('save'); ?>').setForm('eav-attribute').setMethod('post').call()">save</button></td>
		</tr>
	</table>
	<form id="eav-attribute" action="<?php echo $this->getUrl('save','eav_attribute')?>" method="post">
		<table class="table table-bordered">
			<tr>
				<td>Entity Type</td>
				<td><select  name="attribute[entity_type_id]">
					<?php foreach ($entities->getData() as $entity): ?>
					<option value="<?php echo $entity->entity_type_id ?>" <?php  if( $entity->entity_type_id == $row->entity_type_id ){echo 'selected';} ?> ><?php echo $entity->name; ?></option>
					<?php endforeach ?>
				</select></td>
			</tr>
			<tr>
				<td>Code</td>
				<td><input type="text" name="attribute[code]" value="<?php echo $row->code; ?>"></td>
			</tr>
			<tr>
				<td>Name</td>
				<td><input type="text" name="attribute[name]" value="<?php echo $row->name; ?>"></td>
			</tr>
			<tr >
				<td>Input Type</td>
				<td><select  name="attribute[input_type]"  id="inputTypeSelect" >
					<?php foreach ($row->getResource()->getInputTypeOptions() as $key => $value): ?>
					<option value="<?php echo $key ?>" <?php if($row->getInputType() == $key){ echo 'selected'; } ?>><?php echo $value ?></option>
					<?php endforeach; ?>
				</select></td>
			</tr>
			<tr>
				<td>Backend Type</td>
				<td><select  name="attribute[backend_type]" >
					<?php foreach ($row->getResource()->getBackendTypeOptions() as $key => $value): ?>
					<option value="<?php echo $key ?>" <?php if($row->getBackendType() == $key){ echo 'selected'; } ?>><?php echo $value ?></option>
					<?php endforeach; ?>
				</select></td>
			</tr>
			<tr>
				<td>Status</td>
				<td> <select name="attribute[status]" >
					<?php foreach ($row->getStatusOptions() as $key => $value): ?>
					<option value="<?php echo $key ?>" <?php if($row->getstatus() == $key){ echo 'selected'; } ?>><?php echo $value ?></option>
					<?php endforeach; ?>
				</select> </td>
			</tr>
			<tr>
				<td>Backend Model</td>
				<td><input type="text" name="attribute[source_model]" value="<?php echo $row->source_model; ?>"></td>
			</tr>
			<tr>
				<td>&nbsp;</td>
			</tr>
		</table>
		<div style="border:0px ; display: none;margin: 10px 5px;" id="inputTypeOptionBlock">
			<table>
				<thead>
					<tr>
						<th>&nbsp;</th>
						<th><input type="button" name="add" value="ADD" id="addOption"></th>
					</tr>
				</thead>
				<tbody id="inputTypeOptionTable">
					<?php if ($options): ?>
					<?php foreach ($options as $option): ?>
					<tr>
						<td><input type="text" name="old_option[<?php echo $option->option_id; ?>][name]" value="<?php echo $option->name ?>" ></td>
						<td><input type="text" name="old_option[<?php echo $option->option_id; ?>][position]" value="<?php echo $option->position ?>" ></td>
						<td><input type="button" onclick="removeOption(this)" name="remove" value="REMOVE"></td>
					</tr>
					<?php endforeach ?>
					<?php endif ?>
				</tbody>
			</form>
		</table>
	</div>
	<table style="display:none">
		<tbody id="inputTypeOptionDefault">
			
			<td><input type="text" name="new_option[name]" id="newname"></td>
			<td><input type="text" name="new_option[position]" id="newop"></td>
			<td><input type="button" name="remove" onclick="removeOption(this)" value="REMOVE"></td>
			
		</tbody>
	</table>
</div>
<script type="text/javascript">
	$(document).ready(function (){
			var key = 0;
		$("#addOption").click(function(){
			$("#newname").attr('name',"new_option["+key+"][name]" );
			$("#newop").attr('name', "new_option["+key+"][position]");
			$('#inputTypeOptionTable').prepend($('#inputTypeOptionDefault').html());
			key++;
		});
		$('#inputTypeSelect').change(function (){
			var SelectedInputType = $(this);
			const backendTypeArray = ["select", "multiselect", "checkbox", "radio"];
			if(backendTypeArray.includes(SelectedInputType.val())){
				$('#inputTypeOptionBlock').show();
			}
			else{
				$('#inputTypeOptionBlock').hide();
			}
			const backendTypeArray2 = ["textbox", "textarea"];
		});
		$('#inputTypeSelect').trigger('change');
	})
	function removeOption(obj)
	{
		var parent = $(obj).parent().parent().remove();
	}
</script>