<?php
$request = $this->getRequest();
$productId=(int)$request->getParam('product_id');
?>
<button id="subtn" class="btn btn-primary" type="button" onclick="ajax.setUrl('<?php echo $this->getUrl('insert','product_media',['product_id'=>$productId]); ?>').setForm('addimage').setMethod('post').call()">save</button>
<form id="addimage" action="" method="POST" enctype="multipart/form-data">
  <table class="table table-bordered">
    <tr>
      <th>IMAGE</th>
      <td> <input type="file" name="fileToUpload"></td>
    </tr>
    <tr>
    <th>IMAGE NAME</th>
    <td><input type="text" name="media[filename]"></td>
    </tr>
  </table>
</form>
  <input type="button" value="submit" onclick="ajax.setUrl('<?php echo $this->getUrl('insert','product_media',['product_id'=>$productId]); ?>').setForm('addimage').setMethod('post').call()">