<?php
$request = $this->getRequest();
$productId=(int)$request->getParam('product_id');
?>
<form id="addimage" action="<?php echo $this->getUrl('insert','product_media',['product_id'=>$productId]); ?>" method="POST" enctype="multipart/form-data">
<button id="subtn" class="btn btn-primary" type="submit">save</button>
  <table class="table table-bordered">
    <tr>
      <th>IMAGE</th>
      <td> <input type="file" name="fileToUpload"></td>
    </tr>
    <tr>
    <th>IMAGE NAME</th>
    <td><input type="text" name="media[filename]"></td>
    </tr>
  </table>
</form>
  