<tr> <th>BILLING ADDRESS </th></tr>
<tr>
    <th>ADDRESS</th>
    <td><input type="text" name="address2[address]" value="<?php echo $address2->address ?>"></td>
</tr>
<tr>
    <th>CITY</th>
    <td><input type="text" name="address2[city]" value="<?php echo $address2->city ?>"></td>
</tr>
<tr>
    <th>STATE</th>
    <td><input type="text" name="address2[state]" value="<?php echo $address2->state ?>"></td>
</tr>
<th>COUNTRY</th>
<td><input type="text" name="address2[country]" value="<?php echo $address2->country ?>"></td>
</tr>
<tr>
<th>ZIP_CODE</th>
<td><input type="number" name="address2[zip_code]" value="<?php echo $address2->zip_code ?>"></td>
</tr>