<!DOCTYPE html>
<html>
<?php echo $this->createBlock('Html_Head')->toHtml(); ?>
<body>
	<table width="100%">
		<tr rowspan="3"><td colspan="3"><?php  echo $this->getChild('header')->toHtml(); ?></td></tr>
		<tr rowspan="3" height="50px"><td colspan="3" id="message-html"><?php  echo $this->getChild('message')->toHtml(); ?></td></tr>
		<tr height="400"><td><?php  echo $this->getChild('left')->toHtml(); ?></td>
			<td><?php  echo $this->getChild('content')->toHtml(); ?></td>
			<td><?php  echo $this->getChild('right')->toHtml(); ?></td></tr>

		<tr rowspan="3"><td colspan="3" height="100"><?php  echo $this->getChild('footer')->toHtml(); ?></td></tr>
	</table>

</body>
</html>