<?php 
$quoteItemDetails = $this->getQuote()->getQuoteItemDetails();
$total = $this->getTotal();
 ?>
<table class="table table-bordered">
	<tr>
		<td>PRODUCT ID</td>
		<td>NAME</td>
		<td>SKU</td>
		<td>PRICE</td>
		<td>QUANTITY</td>
		<td>DISCCOUNT</td>
		<td>ROW TOTAL</td>
		<td>REMOVE</td>
	</tr>
		<input type="button" onclick="ajax.setUrl('<?php echo $this->getUrl('updateQuantity','quote')?>').setForm('quote').setMethod('post').call()" class="btn btn-primary mx-1" value="update">
		<?php if (!$quoteItemDetails): ?>
		<td colspan="7" >data not found </td>
		<?php else: ?>
		<?php foreach ($quoteItemDetails->getData() as $detail):?>
		<tr>
			<td><?php echo $detail->product_id ?></td>
			<td><?php echo $detail->name ?></td>
			<td><?php echo $detail->sku ?></td>
			<td><?php echo $detail->price ?></td>
			<td> <input type="number" name="product[<?php echo $detail->product_id ?>][quantity]" value="<?php echo $detail->quantity?>">  </td>
			<td> <input type="number" name="product[<?php echo $detail->product_id ?>][discount]" value="<?php echo $detail->discount?>">  </td>
			<td><?php echo ((int)$detail->price * (int)$detail->quantity)-(int)$detail->discount ?></td>
			<td><a onclick="ajax.setUrl('<?php echo $this->getUrl('deleteproduct','quote',['product_id'=>$detail->product_id]) ?>').call()">remove</a></td>
		</tr>
		<?php endforeach; ?>
		<?php endif ?>

	<tr>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td style="text-align: right;">total = </td>
		<td> <?php echo $total?> </td>
	</tr>
</table>