<?php 
$products = $this->getQuote()->getProducts();
?>
	<input type="button" onclick="ajax.setUrl('<?php echo $this->getUrl('addproduct','quote')?>').setForm('quote').setMethod('post').call()" class="btn btn-primary mx-1" value="add">
<table class="table table-bordered">
<tr>
	<td>PRODUCT ID</td>
	<td>NAME</td>
	<td>SKU</td>
	<td>PRICE</td>
	<td>QUANTITY</td>
	<td>ADD</td>
</tr>

<?php foreach ($products->getData() as $product):?>
	<tr>
		<td><?php echo $product->product_id ?></td>
		<td><?php echo $product->name ?></td>
		<td><?php echo $product->sku ?></td>
		<td><?php echo $product->price ?></td>
		<td> <input type="number" name="quantity[<?php echo $product->product_id ?>]" value="" class="quantity">  </td>
		<td><input type="checkbox" value="<?php echo $product->product_id ?>" class="addq"></td>
	</tr>
	<?php endforeach; ?>

<script type="text/javascript">
$(document).ready(function (){
	console.log($('.quantity'));
$('.addq').click(function()
{
	var ind  = ($('.addq').index(this));
	console.log();
if($(this).prop("checked") == true)
{
$('.quantity').eq(ind).attr('value',1);
}
else if($(this).prop("checked") == false)
{
$('.quantity').eq(ind).removeAttr('value',);
}
});

});

</script>
