<?php
$row = $this->getData('customer');
$address  = $row->getShippingAddress();
$address2  = $row->getBillingAddress();
?>
<table>
  <tr>
    <td><h3>Edit customer<h3></td>
    <td><a class="btn btn-primary mx-2" href="<?php echo $this->getModelUrl()->getUrl('grid',null,null,true); ?>">cancel</a> </td>
    <form action="<?php echo $this->getModelUrl()->getUrl('save'); ?>" method="POST">
      <td><button class="btn btn-primary">save</button></td>
    </tr>
  </table>
  <table class="table table-bordered">
    <tr>
      <th>FIRST_NAME</th>   
      <td><input type="text" name="customer[first_name]" value="<?php echo $row->first_name ?>"></td>
    </tr>
    <tr>
      <th>LAST_NAME</th>
      <td><input type="text" name="customer[last_name]" value="<?php echo $row->last_name ?>"></td>
    </tr>
    <tr>
      <th>EMAIL</th>
      <td><input type="email" name="customer[email]" value="<?php echo $row->email ?>"></td>
    </tr>
    <tr>
      <th>GENDER</th>
      <td> <select name="customer[gender]" >
        <option value="male" name="male">male</option>
        <option value="female" name="female">female</option>
      </select> </td>
    </tr>
    <tr>
      <th>MOBILE</th>
      <td><input type="number" name="customer[mobile]" value="<?php echo $row->mobile ?>"></td>
    </tr>
    <tr>
      <th>STATUS</th>
      <td> <select name="customer[status]">
        <?php foreach ($row->getStatusOptions() as $key => $value): ?>
        <option value="<?php echo $key ?>" <?php if($row->getstatus() == $key){ echo 'selected'; } ?>><?php echo $value ?></option>
        <?php endforeach; ?>
      </select> </td>
    </tr>
    <tr>
    <?php if ($this->getAttributes()): ?>
<?php foreach ($this->getAttributes() as $key => $value): ?>
  <tr><th><?php echo$value->name; ?></th>
  <td><?php $this->getLayout()->createBlock("Eav_Attribute_inputType")->setAttribute($value)->setRow($row)->render();?></td><tr>
<?php endforeach ?> 
    <?php endif ?>
</tr>
    <tr>
      <td>shipping address as billing address</td>
      <td><input type="checkbox" id="sameaddress" name="sameaddress" value="1"  <?php if($address->address_id == $address2->address_id){echo 'checked';}?>></td>
    </tr>
    <tr>
      <td>address</td>
    </tr>
    <?php require 'View/customer/address/edit.phtml' ?>
    <div class="showBillingAddresss" style="border:0px ; display: none;">
    <tr class="showBillingAddresss">billing address</tr>
    <table class="showBillingAddresss" class="table table-bordered">
      <?php require_once 'View/customer/address/edit2.phtml' ?>
    </table>
  </div>

  
</form>
</table>
<script type="text/javascript">
$(document).ready(function (){
$('input[type="checkbox"]').click(function()
{
if($(this).prop("checked") == true)
{
$('.showBillingAddresss').hide();
}
else if($(this).prop("checked") == false)
{
$('.showBillingAddresss').show();
}
});
if($("#sameaddress").is(":checked"))
{
$('.showBillingAddresss').hide();
}
});
</script>