<?php
$category = $this->getData('category');
$categoriesData = $this->getData('categoriesData');
?>
<table>
  <tr>
    <td><h3> category<h3></td>
    <td><a class="btn btn-primary mx-2" href="<?php echo $this->getModelUrl()->getUrl('grid',null,null,true); ?>">cancel</a> </td>
    <form action="<?php echo $this->getModelUrl()->getUrl('save'); ?>" method="POST">
      <td><button class="btn btn-primary"> save</button></td>
    </tr>
  </table>
  <table class="table table-bordered">
    <form action="insert_category.php" method="GET">
      <tr> <th>PARENT CATEGORY</th>
      <td><select name="category[parent_id]" >
        <?php foreach ($categoriesData->getData() as $singleCategory): ?>
        <option value="<?php echo $singleCategory->category_id;?>"
          <?php if ($category->parent_id == $singleCategory->category_id)
          { echo "selected";}?> >
          <?php echo $singleCategory->getPathName();?>
        </option>
        <?php endforeach; ?>
      </select> </td></tr>
      <tr>
        <th>NAME</th>
        <td><input type="text" name="category[name]" value="<?php echo $category->name ?>"></td>
      </tr>
      <tr>
        <th>STATUS</th>
        <td> <select name="category[status]" >
          <?php foreach ($category->getResource()->getStatusOptions() as $key => $value): ?>
          <option value="<?php echo $key ?>" <?php if($category->getstatus() == $key){ echo 'selected'; } ?>><?php echo $value ?></option>
          <?php endforeach; ?>
        </select> </td>
      </tr>
      <tr>
        <th>DESCRIPTION</th>
        <td><input type="text" name="category[description]" value="<?php echo $category->description ?>"></td>
      </tr>
    </form>
  </table>