<?php
$row = $this->getRow();
$categoriesData = $this->getCategoriesData();
Ccc::log($categoriesData,'cat.log');
?>
<table>
  <tr>
    <td><h3> category<h3></td>
    <td><a  class="btn btn-primary mx-2" onclick="ajax.setUrl('<?php echo $this->getUrl('grid',null,null,true); ?>').call()">cancel</a> </td>
      <td><button class="btn btn-primary" type="button" onclick="ajax.setUrl('<?php echo $this->getUrl('save'); ?>').setForm('cetegory').setMethod('post').call()" >save</button></td>
    </tr> 
  </table>
    <form id="cetegory" action="" method="POST">
  <table class="table table-bordered">
    <tr> <th>PARENT CATEGORY</th>
    <td><select name="category[parent_id]" >
      <?php if ($categoriesData): ?>
      <?php foreach ($categoriesData->getData() as $singleCategory): ?>
      <option value="<?php echo $singleCategory->category_id;?>"
        <?php if ($row->parent_id == $singleCategory->category_id)
        { echo "selected";}?> >
        <?php echo $singleCategory->getPathName();?>
      </option>
      <?php endforeach; ?>
      <?php endif ?>
    </select> </td></tr>
    <tr>
      <th>NAME</th>
      <td><input type="text" name="category[name]" value="<?php echo $row->name ?>"></td>
    </tr>
    <tr>
      <th>STATUS</th>
      <td> <select name="category[status]" >
        <?php foreach ($row->getStatusOptions() as $key => $value): ?>
        <option value="<?php echo $key ?>" <?php if($row->getstatus() == $key){ echo 'selected'; } ?>><?php echo $value ?></option>
        <?php endforeach; ?>
      </select> </td>
    </tr>
    <tr>
      <th>DESCRIPTION</th>
      <td><input type="text" name="category[description]" value="<?php echo $row->description ?>"></td>
    </tr>
    <tr>
      <?php if ($this->getAttributes()): ?>
      <?php foreach ($this->getAttributes() as $key => $value): ?>
      <tr><th><?php echo $value->name; ?></th>
      <td><?php $this->getLayout()->createBlock("Eav_Attribute_inputType")->setAttribute($value)->setRow($row)->render();?></td><tr>
      <?php endforeach ?>
      <?php endif ?>
    </tr>
  </form>
</table>