<?php
$categories  = $this->getCategories();
?>
<div><h3>CATEGORY</h3></div><div style="margin-left:640px;margin-top: 15px;"><a  class="btn btn-primary" href="<?php echo $this->getModelUrl()->getUrl('add');?>">
add category
</a></button></div></div>
<br>
<table class="table table-bordered">
<tr >
  <th> CATEGORY_ID</th>
  <th> NAME</th>
  <th> PATH</th>
  <th> STATUS</th>
  <th>DESCRIPTION</th>
  <th> </th>
  <th> </th>
</tr>
<?php if (!$categories): ?>
<td colspan="7" >data not found </td>
<?php else:?>
<?php foreach ($categories->getData()  as $category): ?>
<tr>
  <td><?php echo $category->category_id ?></td>
  <td><?php echo  $category->name; ?></td>
  <td><?php echo  $category->getPathName(); ?></td>
  <td><?php echo $category->getstatustext() ?></td>
  <td><?php echo $category->description ?></td>
  <td><a href="<?php echo $this->getModelUrl()->getUrl('edit','category',['category_id'=>$category->category_id]); ?>">edit</a></td>
  <td><a href="<?php echo $this->getModelUrl()->getUrl('delete','category',['category_id'=>$category->category_id]); ?>">delete<a></td>
</tr>
<?php endforeach; ?>
<?php endif;?>
</table>