<?php
$row = $this->getRow();
$address  = $row->getAddress();
?>
<table>
  <tr>
    <td><h3>Edit salesman<h3></td>
    <td><a  class="btn btn-primary mx-2" onclick="ajax.setUrl('<?php echo $this->getUrl('grid',null,null,true); ?>').call()">cancel</a> </td>
      <td><button class="btn btn-primary" type="button" onclick="ajax.setUrl('<?php echo $this->getUrl('save'); ?>').setForm('salesman').setMethod('post').call()" >save</button></td>
    </tr>
  </table>
    <form id="salesman" action="<?php echo $this->getUrl('save'); ?>" method="POST">
  <table class="table table-bordered">
    <tr>
      <th>FIRST_NAME</th>
      <td><input type="text" name="salesman[first_name]" value="<?php echo $row->first_name ?>"></td>
    </tr>
    <tr>
      <th>LAST_NAME</th>
      <td><input type="text" name="salesman[last_name]" value="<?php echo $row->last_name ?>"></td>
    </tr>
    <tr>
      <th>EMAIL</th>
      <td><input type="email" name="salesman[email]" value="<?php echo $row->email ?>"></td>
    </tr>
    <tr>
      <th>GENDER</th>
      <td> <select name="salesman[gender]" >
        <option value="male" name="male">male</option>
        <option value="female" name="female">female</option>
      </select> </td>
    </tr>
    <tr>
      <th>MOBILE</th>
      <td><input type="number" name="salesman[mobile]" value="<?php echo $row->mobile ?>"></td>
    </tr>
    <tr>
      <th>STATUS</th>
      <td> <select name="salesman[status]" >
        <?php foreach ($row->getStatusOptions() as $key => $value): ?>
        <option value="<?php echo $key ?>" <?php if($row->getstatus() == $key){ echo 'selected'; } ?>><?php echo $value ?></option>
        <?php endforeach; ?>
      </select> </td>
    </tr>
    <tr>
      <th>COMPANY</th>
      <td><input type="text" name="salesman[company]" value="<?php echo $row->company ?>"></td>
    </tr>
    <tr>
      <td>address</td>
    </tr>
    <?php require 'View/vendor/address/edit.phtml' ?>

</form>
</table>