<?php
$salesman = $this->getData('salesman');
$address  = $this->getData('salesmanAddress');?>
<!DOCTYPE html>
<table>
  <tr>
    <td><h3>Edit salesman<h3></td>
    <td><a class="btn btn-primary mx-2" href="<?php echo $this->getModelUrl()->getUrl('grid'); ?>&c=salesman">cancel</a> </td>
    <form action="<?php echo $this->getModelUrl()->getUrl('save'); ?>" method="POST">
      <td><button class="btn btn-primary">save</button></td>
    </tr>
  </table>
  <table class="table table-bordered">
    <tr>
      <th> FIRST_NAME</th>
      <td><input type="text" name="salesman[first_name]" value="<?php echo $salesman->first_name ?>"></td>
    </tr>
    <tr>
      <th> LAST_NAME</th>
      <td><input type="text"  name="salesman[last_name]" value="<?php echo $salesman->last_name ?>"></td>
    </tr>
    <tr>
      <th> EMAIL</th>
      <td><input type="email" name="salesman[email]" value="<?php echo $salesman->email ?>"></td>
    </tr>
    <tr>
      <th> GENDER</th>
      <td> <select name="salesman[gender]"   >
        <option value="male"name="male">male</option>
        <option value="female"name="female">female</option>
      </select> </td>
    </tr>
    <tr>
      <th> MOBILE</th>
      <td><input type="mobile" name="salesman[mobile]" value="<?php echo $salesman->mobile ?>"></td>
    </tr>
    <tr>
      <th> STATUS</th>
      <td> <select name="salesman[status]"   >
        <?php foreach ($salesman->getResource()->getStatusOptions() as $key => $value): ?>
        <option value="<?php echo $key ?>"name="available" <?php if($salesman->getstatus() == $key){ echo 'selected'; } ?>><?php echo $value ?></option>
        <?php endforeach; ?>
        
      </select> </td>
    </tr>
    <tr>
      <th> COMPANY</th>
      <td><input type="text" name="salesman[company]" value="<?php echo $salesman->company ?>"></td>
    </tr>
    <tr>
      <td>address</td>
    </tr>
    <?php require 'View/salesman/address/edit.phtml' ?>
  </form>
</table>