<?php
$collection = $this->getCollection();
$pager = $this->getPagerModel();
?>
<div><a  class="btn btn-primary my-1" onclick="ajax.setUrl('<?php echo $this->getUrl('import'); ?>').call()">Import</a>
	<a  class="btn btn-primary my-1" href="<?php echo $this->getUrl('export'); ?>">Export</a>
</div>

<div><div><h3><?php echo $this->getTitle(); ?></h3></div>


<?php foreach ($this->getButtons() as $key => $button): ?>
<div class="add-btn"><a  class="btn btn-primary my-1" onclick="ajax.setUrl('<?php echo $button['url'] ?>').call()">
	<?php echo $button['title'] ?>
</a></div></div>
<?php endforeach ?>
<table class="table table-bordered">
	<tr>
		<?php foreach ($this->getColumns() as $key => $column): ?>
		<th><?php echo $column['title']; ?></th>
		<?php endforeach ?>
		<?php foreach ($this->getActions() as $key => $action): ?>
		<th><?php echo $action['title']; ?></th>
		<?php endforeach ?>
	</tr>
	<?php if (!$collection):?>
	<td colspan="13" >data not found </td>
	<?php else: ?>
	<?php foreach ($collection->getData() as $row): ?>
	<tr>
		<?php foreach ($this->getColumns() as $key => $column): ?>
		<td><?php echo $this->getColumnValue($row,$key) ?></td>
		<?php endforeach ?>
		<?php foreach ($this->getActions() as $key => $action): ?>
		<td><a onclick="ajax.setUrl('<?php $method = $action['method']; echo $this->$method($row,$key); ?>').setMethod('get').call()"><?php echo $action['title'] ?></a></td>
		<?php endforeach ?>
	</tr>
	<?php endforeach; ?>
	<?php endif;?>
</table>

<?php echo $this->getLayout()->createBlock('Core_Pager')->setPagerModel($pager)->toHtml(); ?>