<?php
$collection = $this->getCollection();

?>
<div><div><h3><?php echo $this->getTitle(); ?></h3></div>

<?php foreach ($this->getButtons() as $key => $button): ?>
<div style="margin-left:640px;margin-top: 15px;"><a  class="btn btn-primary" href="<?php echo $button['url'] ?>">
<?php echo $button['title'] ?>
</a></div></div>
<?php endforeach ?>
<table class="table table-bordered">
<tr>
  <?php foreach ($this->getColumns() as $key => $column): ?>
  	<th>
  		<?php echo $column['title'] ?>
  	</th>
  	
  <?php endforeach ?>
</tr>
<?php if (!$collection): ?>
<td colspan="5" >data not found </td>
<?php else:?>
<?php
foreach ($collection as $row): ?>
<tr>
	<?php foreach ($this->getColumns() as $key => $column): ?>
		<td><?php echo $row->$key ?></td>
	<?php endforeach ?>
  <!-- <td><a href="<?php echo $this->getModelUrl()->getUrl('edit', null, ['payment_method_id' => $payment_method->payment_method_id]); ?>">edit</a></td>
  <td><a href="<?php echo $this->getModelUrl()->getUrl('delete', null, ['payment_method_id' => $payment_method->payment_method_id]); ?>?a=delete&c=paymentmethod&payment_method_id=<?php echo $payment_method->payment_method_id ?>">delete<a></td> -->
</tr>
<?php endforeach; ?>
<?php endif;?>
</table>