<form id="addcsv" action="<?php echo $this->getUrl('savefile') ?>" method="POST" enctype="multipart/form-data">
<a class="btn btn-primary my-1" onclick="ajax.setUrl('<?php echo $this->getUrl('grid') ?>').call()">cancel</a>
<button id="subtn" class="btn btn-primary" type="submit">upload</button>
  <table class="table table-bordered">
    <tr>
      <th>upload csv file</th>
      <td> <input type="file" name="fileToUpload" accept=".csv"></td>
    </tr>
  </table>
</form>