<?php $pager = $this->getPagerModel(); 
?>
<div class="pagination-div"> <nav aria-label="Page navigation">
	<ul class="pagination">
		<li class="page-item <?php if(!$pager->getPrevious()){echo 'disabled';} ?>" ><button class="page-link" onclick="ajax.setUrl('<?php  echo $this->getUrl('grid',null,['p'=>$pager->getStart()]) ?>').call()" >Start</button></li>
		<li class="page-item <?php if(!$pager->getPrevious()){echo 'disabled';} ?>"><button class="page-link" onclick="ajax.setUrl('<?php  echo $this->getUrl('grid',null,['p'=>$pager->getPrevious()]) ?>').call()">Previous</button></li>
		<li class="page-item"><button class="page-link" onclick="ajax.setUrl('<?php  echo $this->getUrl('grid',null,['p'=>$pager->getCurrentPage()]) ?>').call()" disabled><?php echo $pager->getCurrentPage(); ?></button></li>
		<li class="page-item <?php if(!$pager->getNext()){echo 'disabled';} ?>"><button class="page-link" onclick="ajax.setUrl('<?php  echo $this->getUrl('grid',null,['p'=>$pager->getNext()]) ?>').call()">Next</button></li>
		<li class="page-item <?php if(!$pager->getNext()){echo 'disabled';} ?>"><button class="page-link" onclick="ajax.setUrl('<?php  echo $this->getUrl('grid',null,['p'=>$pager->getEnd()]) ?>').call()">End</button></li>


		<li class="page-item">
			&nbsp;&nbsp;Records Per Page&nbsp;
			<select onchange="recordsPerPage(this.value)">
				<?php foreach ($pager->getRecordOption() as $key => $value): ?>
					
				<option value="<?php echo $key ?>" <?php if($key == $pager->getRecordPerPage()){ echo 'selected';} ?>><?php echo $value?></option>
				<?php endforeach ?>
			</select>
		</li>
		<li class="page-item">
			&nbsp;&nbsp;&nbsp;Go to:
			<input type="number" value="<?php echo $pager->getCurrentPage() ?>" onchange="goto(this.value)" name="goto" min="<?php echo $pager->getStart() ?>" max="<?php echo $pager->getEnd() ?>">
		</li>
		<li class="page-item">&nbsp;&nbsp;&nbsp;showing <b>Page &nbsp;<?php echo $pager->getCurrentPage(); ?> </b> of&nbsp;<b>Page &nbsp;<?php echo $pager->getNoOfPage(); ?></b> </li>

		<li> &nbsp;&nbsp;	no of records:<?php echo $pager->getTotalRecords(); ?></li>
	</ul>
</nav></div>
<script type="text/javascript">
function goto(value){
	var last = <?php echo $pager->getEnd()  ?>;
	if(value > last)
	{
		value =  <?php echo $pager->getEnd()  ?>;
	}
ajax.setUrl('<?php echo $this->getUrl('grid',null,['recordsPerPage'=>$pager->getRecordPerPage()]); ?>&p='+value).call();
}

function recordsPerPage(val){
ajax.setUrl('<?php echo $this->getUrl('grid',null,['p'=>$pager->getCurrentPage()]); ?>&recordsPerPage='+val).call();

}
</script>